Name = "config-server"

[Filesystem]
# read only paths for the container
ReadOnlyPaths = [
	"/bin/**",
	"/dev/**",
	"/etc/**",
	"/home/config-server/**",
	"/lib/**",
	"/media/**",
	"/mnt/**",
	"/opt/**",
	"/proc/**",
	"/root/**",
	"/run/**",
	"/sbin/**",
	"/srv/**",
	"/sys/**",
	"/usr/**",
	"/var/**",
]

# paths where you want to log on write
LogOnWritePaths = [
	"/**"
]

# paths where you can write
WritablePaths = [
	/tmp/**
]

# allowed executable files for the container
AllowExec = [
	"/usr/lib/jvm/java-1.8-openjdk/jre/bin/java"
]

# denied executable files,It will disabe most of the commands e.g. cat, chmod, sh, curl and so on. The reason is
# I want to secure config-server as much I can, As it is an application which will be used by all other applications to
# interact and get secrets.
DenyExec = [
	"/bin/busybox",
	"/usr/bin/**",
	"/usr/sbin/**",
	"/sbin/**",
]

# allowed capabilities
[Capabilities]
Allow = [
	"chown",
	"dac_override",
	"setuid",
	"setgid",
	"net_bind_service"
]

[Network]
# if you don't need to ping in a container, you can probably
# set Raw to false and deny network raw
Raw = false
Packet = false
Protocols = [
	"tcp",
	"udp",
	"icmp"
]